#!/usr/bin/env npx tsx
/**
 * Sync FancyZones custom-layouts.json to Hammerspoon init.lua zone definitions.
 *
 * Usage:
 *   npx tsx sync-zones.ts <path-to-custom-layouts.json>
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { homedir } from "node:os";

interface Zone {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface ParsedLayout {
  name: string;
  zones: Zone[];
}

interface FancyZonesGridInfo {
  rows: number;
  columns: number;
  "rows-percentage": number[];
  "columns-percentage": number[];
  "cell-child-map": number[][];
}

interface FancyZonesCanvasInfo {
  "ref-width": number;
  "ref-height": number;
  zones: Array<{ X: number; Y: number; width: number; height: number }>;
}

interface FancyZonesLayout {
  name: string;
  type: "grid" | "canvas";
  info: FancyZonesGridInfo | FancyZonesCanvasInfo;
}

interface FancyZonesFile {
  "custom-layouts": FancyZonesLayout[];
}

function parseGridLayout(info: FancyZonesGridInfo): Zone[] {
  const rowPcts = info["rows-percentage"].map((p) => p / 10000);
  const colPcts = info["columns-percentage"].map((p) => p / 10000);
  const cellMap = info["cell-child-map"];

  const rowOffsets = [0];
  for (const p of rowPcts) rowOffsets.push(rowOffsets[rowOffsets.length - 1] + p);

  const colOffsets = [0];
  for (const p of colPcts) colOffsets.push(colOffsets[colOffsets.length - 1] + p);

  const zoneCells = new Map<number, Array<[number, number]>>();
  for (let r = 0; r < info.rows; r++) {
    for (let c = 0; c < info.columns; c++) {
      const idx = cellMap[r][c];
      if (!zoneCells.has(idx)) zoneCells.set(idx, []);
      zoneCells.get(idx)!.push([r, c]);
    }
  }

  const zones: Zone[] = [];
  const sortedKeys = [...zoneCells.keys()].sort((a, b) => a - b);
  for (const idx of sortedKeys) {
    const cells = zoneCells.get(idx)!;
    const minR = Math.min(...cells.map(([r]) => r));
    const maxR = Math.max(...cells.map(([r]) => r));
    const minC = Math.min(...cells.map(([, c]) => c));
    const maxC = Math.max(...cells.map(([, c]) => c));

    const x = colOffsets[minC];
    const y = rowOffsets[minR];
    zones.push({
      x,
      y,
      w: colOffsets[maxC + 1] - x,
      h: rowOffsets[maxR + 1] - y,
    });
  }

  return zones;
}

function parseCanvasLayout(info: FancyZonesCanvasInfo): Zone[] {
  const refW = info["ref-width"];
  const refH = info["ref-height"];
  return info.zones.map((z) => ({
    x: z.X / refW,
    y: z.Y / refH,
    w: z.width / refW,
    h: z.height / refH,
  }));
}

function parseFancyZones(path: string): ParsedLayout[] {
  const data: FancyZonesFile = JSON.parse(readFileSync(path, "utf-8"));
  const results: ParsedLayout[] = [];

  for (const layout of data["custom-layouts"]) {
    let zones: Zone[];
    if (layout.type === "grid") {
      zones = parseGridLayout(layout.info as FancyZonesGridInfo);
    } else if (layout.type === "canvas") {
      zones = parseCanvasLayout(layout.info as FancyZonesCanvasInfo);
    } else {
      console.warn(`Warning: unknown layout type '${layout.type}' for '${layout.name}', skipping`);
      continue;
    }
    results.push({ name: layout.name, zones });
  }

  return results;
}

function generateLua(layouts: ParsedLayout[]): string {
  const lines: string[] = [
    "-- Auto-generated by sync-zones.ts from FancyZones custom-layouts.json",
    "-- Do not edit manually; re-run the sync script to update.",
    "",
    "return {",
  ];

  for (const layout of layouts) {
    lines.push(`  -- ${layout.name}`);
    lines.push("  {");
    lines.push(`    name = "${layout.name}",`);
    lines.push("    zones = {");
    layout.zones.forEach((z, i) => {
      lines.push(
        `      { x = ${z.x.toFixed(4)}, y = ${z.y.toFixed(4)}, ` +
          `w = ${z.w.toFixed(4)}, h = ${z.h.toFixed(4)} },  -- ${i + 1}`
      );
    });
    lines.push("    },");
    lines.push("  },");
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

function main(): void {
  const fzPath = process.argv[2];
  if (!fzPath) {
    console.error(`Usage: npx tsx sync-zones.ts <path-to-custom-layouts.json>`);
    process.exit(1);
  }

  const layoutsPath = resolve("./.layouts.lua");

  const parsed = parseFancyZones(fzPath);
  console.log(`Parsed ${parsed.length} layout(s) from FancyZones:`);
  for (const layout of parsed) {
    console.log(`  - ${layout.name} (${layout.zones.length} zones)`);
  }

  writeFileSync(layoutsPath, generateLua(parsed));
  console.log(`\nUpdated ${layoutsPath}`);
  console.log("Reload Hammerspoon config to apply changes.");
}

main();
